import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Header from "../components/Header/Header";
import Brand from "../components/Brand/Brand";
import EarlyAccess from "../components/EarlyAccess/EarlyAccess";
import CTA from "../components/CTA/CTA";

import VRSection from "../components/VRSection/VRSection";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.gradient_bg}>
        <Header />
      </div>

      <CTA />
      <VRSection />
      <EarlyAccess />
      <Brand />
    </div>
  );
}
