import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import Header from "../components/Container/Header/Header";
import Brand from "../components/Brand/Brand";
import WHATGPT3 from "../components/Container/WHATGPT3/WHATGPT3";
import Features from "../components/Container/Features/Features";
import Possibility from "../components/Container/Possibility/Possibility";
import CTA from "../components/CTA/CTA";
import Blog from "../components/Container/Blog/Blog";
import Footer from "../components/Container/Footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.gradient_bg}>
        <Navbar />
        <Header />
      </div>
      <Brand />
      <WHATGPT3 />
      <Features />
      <Possibility />
      <CTA />
      <Blog />
      <Footer />
      <main>GPT-3</main>
    </div>
  );
}
